# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Credit Limit Checkout UI"
client_id = "{INSERT YOUR APP CLIENT ID HERE}"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_metaobject_definitions,read_metaobjects,unauthenticated_read_customers,unauthenticated_read_metaobjects,customer_read_customers,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "checkout-credit-limit-ui.myshopify.com"
